CREATE DATABASE IF NOT EXISTS `SMART INVENTORY MANAGEMENT AND SALES FORECASTING SYSTEM`;

USE `SMART INVENTORY MANAGEMENT AND SALES FORECASTING SYSTEM`;

CREATE TABLE `ITEM TYPES` (
    `ITEM TYPE ID` INT AUTO_INCREMENT UNIQUE,
    `ITEM TYPE` VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY
);

CREATE TABLE `ITEM CATEGORIES` (
    `ITEM CATEGORY ID` INT AUTO_INCREMENT UNIQUE,
    `ITEM CATEGORY` VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY
);

CREATE TABLE `ITEM SUBCATEGORIES` (
    `ITEM SUBCATEGORY ID` INT AUTO_INCREMENT UNIQUE,
    `ITEM SUBCATEGORY` VARCHAR(100) NOT NULL UNIQUE PRIMARY KEY
);

CREATE TABLE `PAYMENT MODES` (
    `PAYMENT MODE ID` INT AUTO_INCREMENT UNIQUE,
    `PAYMENT MODE` VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY
);

CREATE TABLE `COUNTIES` (
    `COUNTY ID` INT AUTO_INCREMENT UNIQUE,
    `COUNTY` VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY
);

CREATE TABLE `TOWNS` (
    `TOWN ID` INT AUTO_INCREMENT UNIQUE,
    `TOWN` VARCHAR(100) NOT NULL UNIQUE PRIMARY KEY	
);

CREATE TABLE `PAYMENT STATUSES` (
    `PAYMENT STATUS ID` INT AUTO_INCREMENT UNIQUE,
    `PAYMENT STATUS` VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY
);

CREATE TABLE `RECEIPT STATUSES` (
    `RECEIPT STATUS ID` INT AUTO_INCREMENT UNIQUE,
    `RECEIPT STATUS` VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY
);

CREATE TABLE `SHIPPING STATUSES` (
    `SHIPPING STATUS ID` INT AUTO_INCREMENT UNIQUE, 
    `SHIPPING STATUS` VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY
);

CREATE TABLE `USER ROLES` (
	`ROLE ID`INT AUTO_INCREMENT UNIQUE,
    `USER ROLE` VARCHAR(50) NOT NULL UNIQUE PRIMARY KEY
);

CREATE TABLE `INVENTORY`(
    `ITEM ID` VARCHAR(7) NOT NULL UNIQUE PRIMARY KEY,
    `ITEM TYPE` VARCHAR(50) NOT NULL,
    `ITEM CATEGORY` VARCHAR(50) NOT NULL,
    `ITEM SUBCATEGORY` VARCHAR(50) NOT NULL,
    `ITEM NAME` VARCHAR(100) NOT NULL,

    -- It is preferrable to add a table for `INVENTORY ITEMS` in order to reference the purchase and sales prices if at all they do change
    `PURCHASE PRICE` DECIMAL(12,2) DEFAULT 0,
    `SALE PRICE` DECIMAL(12,2) DEFAULT 0,
    
    `QUANTITY PURCHASED` INT DEFAULT 0,
    `QUANTITY SOLD` INT DEFAULT 0,
    `QUANTITY REMAINING` INT GENERATED ALWAYS AS (`QUANTITY PURCHASED` - `QUANTITY SOLD`) STORED,

    `REORDER LEVEL` INT DEFAULT 0,
    `REORDER REQUIRED` ENUM('YES','NO') DEFAULT 'NO',

    CONSTRAINT `ITEM TYPE REFERENCE` FOREIGN KEY (`ITEM TYPE`) REFERENCES `ITEM TYPES`(`ITEM TYPE`),
    CONSTRAINT `ITEM CATEGORY REFERENCE` FOREIGN KEY (`ITEM CATEGORY`) REFERENCES `ITEM CATEGORIES`(`ITEM CATEGORY`),
    CONSTRAINT `ITEM SUBCATEGORY REFERENCE` FOREIGN KEY (`ITEM SUBCATEGORY`) REFERENCES `ITEM SUBCATEGORIES`(`ITEM SUBCATEGORY`)
);

-- Create a trigger for identifying whether the reoder is required 
DELIMITER //
CREATE TRIGGER `SET REORDER REQUIRED`
BEFORE INSERT ON `INVENTORY`
FOR EACH ROW
BEGIN
    IF NEW.`QUANTITY REMAINING`<= NEW.`REORDER LEVEL` THEN
        SET NEW.`REORDER REQUIRED` = 'YES';
    ELSE
        SET NEW.`REORDER REQUIRED` = 'NO';
    END IF;
END//
DELIMITER ;

-- Create a trigger for updating the status of whether the reoder is required 
DELIMITER //
CREATE TRIGGER `UPDATE REORDER REQUIRED`
BEFORE UPDATE ON `INVENTORY`
FOR EACH ROW
BEGIN
    IF NEW.`QUANTITY REMAINING` <= NEW.`REORDER LEVEL` THEN
        SET NEW.`REORDER REQUIRED` = 'YES';
    ELSE
        SET NEW.`REORDER REQUIRED` = 'NO';
    END IF;
END//
DELIMITER ;

CREATE TABLE `INVENTORY ITEMS`(
    `ITEM ID` VARCHAR(7) NOT NULL UNIQUE PRIMARY KEY,
    `ITEM TYPE` VARCHAR(50) NOT NULL,
    `ITEM CATEGORY` VARCHAR(50) NOT NULL,
    `ITEM SUBCATEGORY` VARCHAR(50) NOT NULL,
    `ITEM NAME` VARCHAR(100) NOT NULL,
    `PURCHASE PRICE` DECIMAL(12,2) DEFAULT 0,
    `SALE PRICE` DECIMAL(12,2) DEFAULT 0,
    
    CONSTRAINT `ITEM TYPE-INVENTORY ITEMS REFERENCE` FOREIGN KEY (`ITEM TYPE`) REFERENCES `ITEM TYPES`(`ITEM TYPE`),
    CONSTRAINT `ITEM CATEGORY-INVENTORY ITEMS REFERENCE` FOREIGN KEY (`ITEM CATEGORY`) REFERENCES `ITEM CATEGORIES`(`ITEM CATEGORY`),
    CONSTRAINT `ITEM SUBCATEGORY-INVENTORY ITEMS REFERENCE` FOREIGN KEY (`ITEM SUBCATEGORY`) REFERENCES `ITEM SUBCATEGORIES`(`ITEM SUBCATEGORY`)
);

CREATE TABLE `SUPPLIERS` (
    `SUPPLIER ID` VARCHAR(6) NOT NULL UNIQUE PRIMARY KEY,
    `SUPPLIER NAME` VARCHAR(100) NOT NULL,
    `PHONE NUMBER` VARCHAR(30),
    `E-MAIL` VARCHAR(255),

    `COUNTY` VARCHAR(50),
    `TOWN` VARCHAR(50),

    `TOTAL PURCHASES` DECIMAL(12,2) DEFAULT 0,
    `TOTAL PAYMENTS` DECIMAL(12,2) DEFAULT 0,
    `BALANCE PAYABLE` DECIMAL(12,2) GENERATED ALWAYS AS (`TOTAL PURCHASES` - `TOTAL PAYMENTS`) STORED,

    CONSTRAINT `SUPPLIER COUNTY REFERENCE` FOREIGN KEY (`COUNTY`) REFERENCES `COUNTIES`(`COUNTY`),
    CONSTRAINT `SUPPLIER TOWN REFERENCE` FOREIGN KEY (`TOWN`) REFERENCES `TOWNS`(`TOWN`)
);

CREATE TABLE `CUSTOMERS` (
    `CUSTOMER ID` VARCHAR(6) NOT NULL UNIQUE PRIMARY KEY,
    `CUSTOMER NAME` VARCHAR(100) NOT NULL,
    `PHONE NUMBER` VARCHAR(30),
    `E-MAIL` VARCHAR(255),

    `COUNTY` VARCHAR(50),
    `TOWN` VARCHAR(50),

    `TOTAL SALES` DECIMAL(12,2) DEFAULT 0,
    `TOTAL PAYMENTS` DECIMAL(12,2) DEFAULT 0,
    `BALANCE PAYABLE` DECIMAL(12,2) GENERATED ALWAYS AS (`TOTAL SALES` - `TOTAL PAYMENTS`) STORED,

	CONSTRAINT `CUSTOMER COUNTY REFERENCE` FOREIGN KEY (`COUNTY`) REFERENCES `COUNTIES`(`COUNTY`),
    CONSTRAINT `CUSTOMER TOWN REFERENCE` FOREIGN KEY (`TOWN`) REFERENCES `TOWNS`(`TOWN`)
);

CREATE TABLE `PURCHASE ORDERS` (
    `PO ID` VARCHAR(7) NOT NULL UNIQUE PRIMARY KEY,
    `DATE` DATE NOT NULL,

    `SUPPLIER ID` VARCHAR(6) NOT NULL,
    `SUPPLIER NAME` VARCHAR(100) NOT NULL,
    `BILL NUMBER` VARCHAR(6) NOT NULL UNIQUE,

	`COUNTY` VARCHAR(50),
    `TOWN` VARCHAR(50),

	`TOTAL AMOUNT` DECIMAL(12,2) DEFAULT 0,
    `AMOUNT PAID` DECIMAL(12,2) DEFAULT 0,
    `BALANCE LEFT` DECIMAL(12,2) GENERATED ALWAYS AS (`TOTAL AMOUNT` - `AMOUNT PAID`) STORED,

    `PAYMENT STATUS` VARCHAR(50),
    `SHIPPING STATUS` VARCHAR(50),

    CONSTRAINT `PURCHASE ORDER-SUPPLIER REFERENCE` FOREIGN KEY (`SUPPLIER ID`) REFERENCES `SUPPLIERS`(`SUPPLIER ID`),
    CONSTRAINT `PURCHASE ORDER-COUNTY REFERENCE` FOREIGN KEY (`COUNTY`) REFERENCES `COUNTIES`(`COUNTY`),
    CONSTRAINT `PURCHASE ORDER-TOWN REFERENCE` FOREIGN KEY (`TOWN`) REFERENCES `TOWNS`(`TOWN`),
    CONSTRAINT `PURCHASE ORDER-PAYMENT STATUS REFERENCE` FOREIGN KEY (`PAYMENT STATUS`) REFERENCES `PAYMENT STATUSES`(`PAYMENT STATUS`),
    CONSTRAINT `PURCHASE ORDER-SHIPPING STATUS REFERENCE` FOREIGN KEY (`SHIPPING STATUS`) REFERENCES `SHIPPING STATUSES`(`SHIPPING STATUS`)
);

CREATE TABLE `SALES ORDERS` (
    `SO ID` VARCHAR(7) NOT NULL UNIQUE PRIMARY KEY,
    `DATE` DATE NOT NULL,

    `CUSTOMER ID` VARCHAR(6) NOT NULL,
    `CUSTOMER NAME` VARCHAR(100) NOT NULL,
    `INVOICE NUMBER` VARCHAR(6) NOT NULL UNIQUE,

	`COUNTY` VARCHAR(50),
    `TOWN` VARCHAR(50),

	`TOTAL AMOUNT` DECIMAL(12,2) DEFAULT 0,
    `AMOUNT RECEIVED` DECIMAL(12,2) DEFAULT 0,
    `BALANCE LEFT` DECIMAL(12,2) GENERATED ALWAYS AS (`TOTAL AMOUNT` - `AMOUNT RECEIVED`) STORED,

    `RECEIPT STATUS` VARCHAR(50),
    `SHIPPING STATUS` VARCHAR(50),

    CONSTRAINT `SALES ORDER-CUSTOMER REFERENCE` FOREIGN KEY (`CUSTOMER ID`) REFERENCES `CUSTOMERS`(`CUSTOMER ID`),
    CONSTRAINT `SALES ORDER-COUNTY REFERENCE` FOREIGN KEY (`COUNTY`) REFERENCES `COUNTIES`(`COUNTY`),
    CONSTRAINT `SALES ORDER-TOWN REFERENCE` FOREIGN KEY (`TOWN`) REFERENCES `TOWNS`(`TOWN`),
    CONSTRAINT `SALES ORDER-RECEIPT STATUS REFERENCE` FOREIGN KEY (`RECEIPT STATUS`) REFERENCES `RECEIPT STATUSES`(`RECEIPT STATUS`),
    CONSTRAINT `SALES ORDER-SHIPPING STATUS REFERENCE` FOREIGN KEY (`SHIPPING STATUS`) REFERENCES `SHIPPING STATUSES`(`SHIPPING STATUS`)
);

CREATE TABLE `PURCHASE DETAILS` (
    `DETAIL ID` VARCHAR(7) NOT NULL UNIQUE PRIMARY KEY,
	`PO ID` VARCHAR(7) NOT NULL, 	
	`DATE` DATE NOT NULL,
        
    `SUPPLIER ID` VARCHAR(6) NOT NULL,
    `SUPPLIER NAME` VARCHAR(100) NOT NULL,
    `COUNTY` VARCHAR(50),
    `TOWN` VARCHAR(50),
    
    `BILL NUMBER` VARCHAR(6) NOT NULL,
    
    `ITEM ID` VARCHAR(7) NOT NULL,
    `ITEM TYPE` TEXT(50) NOT NULL,
    `ITEM CATEGORY` TEXT(50) NOT NULL,
    `ITEM SUBCATEGORY` TEXT(50) NOT NULL,
    `ITEM NAME` VARCHAR(100) NOT NULL,
    
    `QUANTITY PURCHASED` INT NOT NULL,
    `UNIT COST` DECIMAL(12,2) NOT NULL,
    `COST EXCLUDING TAX` DECIMAL(12,2) GENERATED ALWAYS AS (`QUANTITY PURCHASED` * `UNIT COST`) STORED,
    `TAX RATE` DECIMAL(5,2) DEFAULT 0,
    `TOTAL TAX` DECIMAL(12,2) GENERATED ALWAYS AS (`COST EXCLUDING TAX` * `TAX RATE`/100) STORED,
    `COST INCLUDING TAX` DECIMAL(12,2) GENERATED ALWAYS AS (`COST EXCLUDING TAX` + `TOTAL TAX`) STORED,
    `SHIPPING FEES` DECIMAL(12,2) GENERATED ALWAYS AS (`COST INCLUDING TAX` * 1/100) STORED,
    `TOTAL PURCHASE PRICE` DECIMAL(12,2) GENERATED ALWAYS AS (`COST INCLUDING TAX` + `SHIPPING FEES`) STORED,

    CONSTRAINT `PURCHASE DETAIL-PURCHASE ORDER REFERENCE` FOREIGN KEY (`PO ID`) REFERENCES `PURCHASE ORDERS`(`PO ID`),
    CONSTRAINT `PURCHASE DETAILS-ITEM REFERENCE` FOREIGN KEY (`ITEM ID`) REFERENCES `INVENTORY`(`ITEM ID`),
    CONSTRAINT `PURCHASE DETAILS-SUPPLIER COUNTY REFERENCE` FOREIGN KEY (`COUNTY`) REFERENCES `COUNTIES`(`COUNTY`),
    CONSTRAINT `PURCHASE DETAILS-SUPPLIER TOWN REFERENCE` FOREIGN KEY (`TOWN`) REFERENCES `TOWNS`(`TOWN`)
);

CREATE TABLE `SALES DETAILS` (
    `DETAIL ID` VARCHAR(7) NOT NULL UNIQUE PRIMARY KEY,
	`SO ID` VARCHAR(7) NOT NULL, 	
	`DATE` DATE NOT NULL,
        
    `CUSTOMER ID` VARCHAR(6) NOT NULL,
    `CUSTOMER NAME` VARCHAR(100) NOT NULL,
    `COUNTY` VARCHAR(50),
    `TOWN` VARCHAR(50),
    
    `INVOICE NUMBER` VARCHAR(6) NOT NULL,
    
    `ITEM ID` VARCHAR(7) NOT NULL,
    `ITEM TYPE` TEXT(50) NOT NULL,
    `ITEM CATEGORY` TEXT(50) NOT NULL,
    `ITEM SUBCATEGORY` TEXT(50) NOT NULL,
    `ITEM NAME` VARCHAR(100) NOT NULL,
    
    `QUANTITY SOLD` INT NOT NULL,
    `UNIT PRICE` DECIMAL(12,2) NOT NULL,
    `PRICE EXCLUDING TAX` DECIMAL(12,2) GENERATED ALWAYS AS (`QUANTITY SOLD` * `UNIT PRICE`) STORED,
    `TAX RATE` DECIMAL(5,2) DEFAULT 0,
    `TOTAL TAX` DECIMAL(12,2) GENERATED ALWAYS AS (`PRICE EXCLUDING TAX` * `TAX RATE`/100) STORED,
    `PRICE INCLUDING TAX` DECIMAL(12,2) GENERATED ALWAYS AS (`PRICE EXCLUDING TAX` + `TOTAL TAX`) STORED,
    `SHIPPING FEES` DECIMAL(12,2) GENERATED ALWAYS AS (`PRICE INCLUDING TAX` * 2/100) STORED,
    `TOTAL SALES PRICE` DECIMAL(12,2) GENERATED ALWAYS AS (`PRICE INCLUDING TAX` + `SHIPPING FEES`) STORED,

    CONSTRAINT `SALES DETAIL-SALES ORDER REFERENCE` FOREIGN KEY (`SO ID`) REFERENCES `SALES ORDERS`(`SO ID`),
    CONSTRAINT `SALES DETAILS-ITEM REFERENCE` FOREIGN KEY (`ITEM ID`) REFERENCES `INVENTORY`(`ITEM ID`),
    CONSTRAINT `SALES DETAILS-CUSTOMER COUNTY REFERENCE` FOREIGN KEY (`COUNTY`) REFERENCES `COUNTIES`(`COUNTY`),
    CONSTRAINT `SALES DETAILS-CUSTOMER TOWN REFERENCE` FOREIGN KEY (`TOWN`) REFERENCES `TOWNS`(`TOWN`)
);

CREATE TABLE `PAYMENTS` (
    `TRANSACTION ID` VARCHAR(13) NOT NULL UNIQUE PRIMARY KEY,
    `DATE` DATE NOT NULL,

	`SUPPLIER ID` VARCHAR(6) NOT NULL,
    `SUPPLIER NAME` VARCHAR(100) NOT NULL,
    `COUNTY` VARCHAR(50),
    `TOWN` VARCHAR(50),
    
    `PO ID` VARCHAR(7) NOT NULL, 
    `BILL NUMBER` VARCHAR(6) NOT NULL,
    
    `PAYMENT MODE` VARCHAR(50) NOT NULL,
    `AMOUNT PAID` DECIMAL(12,2) NOT NULL,

    CONSTRAINT `PAYMENT-SUPPLIER REFERENCE` FOREIGN KEY (`SUPPLIER ID`) REFERENCES `SUPPLIERS`(`SUPPLIER ID`),
    CONSTRAINT `PAYMENT-PURCHASE ORDER REFERENCE` FOREIGN KEY (`PO ID`) REFERENCES `PURCHASE ORDERS`(`PO ID`),
    CONSTRAINT `PAYMENT-PAYMENT MODE REFERENCE` FOREIGN KEY (`PAYMENT MODE`) REFERENCES `PAYMENT MODES`(`PAYMENT MODE`)
);

CREATE TABLE `RECEIPTS` (
    `TRANSACTION ID` VARCHAR(12) NOT NULL UNIQUE PRIMARY KEY,
    `DATE` DATE NOT NULL,

	`CUSTOMER ID` VARCHAR(6) NOT NULL,
    `CUSTOMER NAME` VARCHAR(100) NOT NULL,
    `COUNTY` VARCHAR(50),
    `TOWN` VARCHAR(50),
    
    `SO ID` VARCHAR(7) NOT NULL, 
    `INVOICE NUMBER` VARCHAR(6) NOT NULL,
    
    `PAYMENT MODE` VARCHAR(50) NOT NULL,
    `AMOUNT RECEIVED` DECIMAL(12,2) NOT NULL,

    CONSTRAINT `RECEIPT-CUSTOMER REFERENCE` FOREIGN KEY (`CUSTOMER ID`) REFERENCES `CUSTOMERS`(`CUSTOMER ID`),
    CONSTRAINT `RECEIPT-SALES ORDER REFERENCE` FOREIGN KEY (`SO ID`) REFERENCES `SALES ORDERS`(`SO ID`),
    CONSTRAINT `RECEIPT-PAYMENT MODE REFERENCE` FOREIGN KEY (`PAYMENT MODE`) REFERENCES `PAYMENT MODES`(`PAYMENT MODE`)
);

CREATE TABLE `USERS` (
	`FULL NAME` VARCHAR(100) NOT NULL, 
    `E-MAIL` VARCHAR(100) NOT NULL UNIQUE PRIMARY KEY,
    `PHONE NUMBER` VARCHAR(12) NOT NULL,
    `PASSWORD` VARCHAR(25) NOT NULL,
    `USER ROLE` VARCHAR(50) NOT NULL,
    
    CONSTRAINT `USER ROLE REFERENCE` FOREIGN KEY (`USER ROLE`) REFERENCES `USER ROLES`(`USER ROLE`)
);

