# Generated by Django 5.2.9 on 2026-01-07 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('county', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'County',
                'verbose_name_plural': 'Counties',
                'db_table': 'COUNTIES',
            },
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('item_category', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Item Category',
                'verbose_name_plural': 'Item Categories',
                'db_table': 'ITEM_CATEGORIES',
            },
        ),
        migrations.CreateModel(
            name='ItemSubcategory',
            fields=[
                ('item_subcategory', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Item Subcategory',
                'verbose_name_plural': 'Item Subcategories',
                'db_table': 'ITEM_SUBCATEGORIES',
            },
        ),
        migrations.CreateModel(
            name='ItemType',
            fields=[
                ('item_type', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Item Type',
                'verbose_name_plural': 'Item Types',
                'db_table': 'ITEM_TYPES',
            },
        ),
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('payment_mode', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Payment Mode',
                'verbose_name_plural': 'Payment Modes',
                'db_table': 'PAYMENT_MODES',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('payment_status', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Payment Status',
                'verbose_name_plural': 'Payment Statuses',
                'db_table': 'PAYMENT_STATUSES',
            },
        ),
        migrations.CreateModel(
            name='ReceiptStatus',
            fields=[
                ('receipt_status', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Receipt Status',
                'verbose_name_plural': 'Receipt Statuses',
                'db_table': 'RECEIPT_STATUSES',
            },
        ),
        migrations.CreateModel(
            name='ShippingStatus',
            fields=[
                ('shipping_status', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Shipping Status',
                'verbose_name_plural': 'Shipping Statuses',
                'db_table': 'SHIPPING_STATUSES',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('town', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'Town',
                'verbose_name_plural': 'Towns',
                'db_table': 'TOWNS',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_role', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'USER_ROLES',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('county', models.ForeignKey(blank=True, db_column='COUNTY', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.county')),
                ('town', models.ForeignKey(blank=True, db_column='TOWN', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.town')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'CUSTOMERS',
            },
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('item_id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item_category', models.ForeignKey(db_column='ITEM_CATEGORY', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.itemcategory')),
                ('item_subcategory', models.ForeignKey(db_column='ITEM_SUBCATEGORY', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.itemsubcategory')),
                ('item_type', models.ForeignKey(db_column='ITEM_TYPE', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.itemtype')),
            ],
            options={
                'verbose_name': 'Inventory Item Master',
                'verbose_name_plural': 'Inventory Items Master',
                'db_table': 'INVENTORY_ITEMS',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('item_id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('item_name', models.CharField(max_length=100)),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity_purchased', models.IntegerField(default=0)),
                ('quantity_sold', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=0)),
                ('reorder_required', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=3)),
                ('item_category', models.ForeignKey(db_column='ITEM_CATEGORY', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.itemcategory')),
                ('item_subcategory', models.ForeignKey(db_column='ITEM_SUBCATEGORY', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.itemsubcategory')),
                ('item_type', models.ForeignKey(db_column='ITEM_TYPE', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.itemtype')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory',
                'db_table': 'INVENTORY',
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('so_id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=6, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_received', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('county', models.ForeignKey(blank=True, db_column='COUNTY', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.county')),
                ('customer_id', models.ForeignKey(db_column='CUSTOMER_ID', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.customer')),
                ('receipt_status', models.ForeignKey(blank=True, db_column='RECEIPT_STATUS', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.receiptstatus')),
                ('shipping_status', models.ForeignKey(blank=True, db_column='SHIPPING_STATUS', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.shippingstatus')),
                ('town', models.ForeignKey(blank=True, db_column='TOWN', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.town')),
            ],
            options={
                'verbose_name': 'Sales Order',
                'verbose_name_plural': 'Sales Orders',
                'db_table': 'SALES_ORDERS',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('supplier_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('total_purchases', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('county', models.ForeignKey(blank=True, db_column='COUNTY', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.county')),
                ('town', models.ForeignKey(blank=True, db_column='TOWN', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.town')),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
                'db_table': 'SUPPLIERS',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('po_id', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('supplier_name', models.CharField(max_length=100)),
                ('bill_number', models.CharField(max_length=6, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('county', models.ForeignKey(blank=True, db_column='COUNTY', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.county')),
                ('payment_status', models.ForeignKey(blank=True, db_column='PAYMENT_STATUS', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.paymentstatus')),
                ('shipping_status', models.ForeignKey(blank=True, db_column='SHIPPING_STATUS', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.shippingstatus')),
                ('supplier_id', models.ForeignKey(db_column='SUPPLIER_ID', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.supplier')),
                ('town', models.ForeignKey(blank=True, db_column='TOWN', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.town')),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Orders',
                'db_table': 'PURCHASE_ORDERS',
            },
        ),
        migrations.CreateModel(
            name='SalesDetail',
            fields=[
                ('detail_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=6)),
                ('item_type', models.CharField(max_length=50)),
                ('item_category', models.CharField(max_length=50)),
                ('item_subcategory', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity_sold', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('county', models.ForeignKey(blank=True, db_column='COUNTY', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.county')),
                ('customer_id', models.ForeignKey(db_column='CUSTOMER_ID', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.customer')),
                ('item_id', models.ForeignKey(db_column='ITEM_ID', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.inventory')),
                ('so_id', models.ForeignKey(db_column='SO_ID', on_delete=django.db.models.deletion.CASCADE, to='INVENTORY_MANAGEMENT.salesorder')),
                ('town', models.ForeignKey(blank=True, db_column='TOWN', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.town')),
            ],
            options={
                'verbose_name': 'Sales Detail',
                'verbose_name_plural': 'Sales Details',
                'db_table': 'SALES_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('transaction_id', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=6)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('county', models.ForeignKey(blank=True, db_column='COUNTY', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.county')),
                ('customer_id', models.ForeignKey(db_column='CUSTOMER_ID', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.customer')),
                ('payment_mode', models.ForeignKey(db_column='PAYMENT_MODE', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.paymentmode')),
                ('so_id', models.ForeignKey(db_column='SO_ID', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.salesorder')),
                ('town', models.ForeignKey(blank=True, db_column='TOWN', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.town')),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'db_table': 'RECEIPTS',
            },
        ),
        migrations.CreateModel(
            name='PurchaseDetail',
            fields=[
                ('detail_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('supplier_name', models.CharField(max_length=100)),
                ('bill_number', models.CharField(max_length=6)),
                ('item_type', models.CharField(max_length=50)),
                ('item_category', models.CharField(max_length=50)),
                ('item_subcategory', models.CharField(max_length=50)),
                ('item_name', models.CharField(max_length=100)),
                ('quantity_purchased', models.IntegerField()),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('county', models.ForeignKey(blank=True, db_column='COUNTY', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.county')),
                ('item_id', models.ForeignKey(db_column='ITEM_ID', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.inventory')),
                ('po_id', models.ForeignKey(db_column='PO_ID', on_delete=django.db.models.deletion.CASCADE, to='INVENTORY_MANAGEMENT.purchaseorder')),
                ('supplier_id', models.ForeignKey(db_column='SUPPLIER_ID', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.supplier')),
                ('town', models.ForeignKey(blank=True, db_column='TOWN', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.town')),
            ],
            options={
                'verbose_name': 'Purchase Detail',
                'verbose_name_plural': 'Purchase Details',
                'db_table': 'PURCHASE_DETAILS',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('transaction_id', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('supplier_name', models.CharField(max_length=100)),
                ('bill_number', models.CharField(max_length=6)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('county', models.ForeignKey(blank=True, db_column='COUNTY', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.county')),
                ('payment_mode', models.ForeignKey(db_column='PAYMENT_MODE', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.paymentmode')),
                ('po_id', models.ForeignKey(db_column='PO_ID', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.purchaseorder')),
                ('supplier_id', models.ForeignKey(db_column='SUPPLIER_ID', on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.supplier')),
                ('town', models.ForeignKey(blank=True, db_column='TOWN', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.town')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'PAYMENTS',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('phone_number', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('user_role', models.ForeignKey(blank=True, db_column='USER_ROLE', null=True, on_delete=django.db.models.deletion.PROTECT, to='INVENTORY_MANAGEMENT.userrole')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'USERS',
            },
        ),
    ]
