# Generated by Django 5.2.9 on 2026-01-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('INVENTORY_MANAGEMENT', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedetail',
            name='detail_id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='salesdetail',
            name='detail_id',
            field=models.CharField(max_length=7, primary_key=True, serialize=False, unique=True),
        ),
    ]
